apiVersion: v1
kind: Service
metadata:
  name: ensembl-graphql-server-svc
  labels:
    app: ensembl-graphql-server-svc
spec:
  selector:
    app: ensembl-graphql-server
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 5000